"""
Django settings for IMDb project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(key, default=False):
    return os.getenv(key, str(default)).lower() in ('1', 'true', 'yes', 'on')


# SECRET KEY: prod da env'siz ishga tushirmaymiz (xavfsizlik)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
DEBUG = env_bool('DJANGO_DEBUG', True)
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-hikba3xo6(f=#^tyo)e=l*-jt-j6+a4l+_)$32@7q33@wnymb'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured('DJANGO_SECRET_KEY env da bo\'lishi shart (prod uchun)')

DEFAULT_ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']
ALLOWED_HOSTS = [
    host.strip()
    for host in [
        *DEFAULT_ALLOWED_HOSTS,
        *[h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()],
    ]
    if host.strip()
]
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))
if not DEBUG and not ALLOWED_HOSTS:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS prod da ko\'rsatilishi shart')

DEFAULT_CSRF_ORIGINS = [
    'http://localhost',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://[::1]',
    'http://[::1]:8000',
    'https://localhost',
    'https://localhost:8000',
    'https://127.0.0.1',
    'https://127.0.0.1:8000',
    'https://[::1]',
    'https://[::1]:8000',
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in [
        *DEFAULT_CSRF_ORIGINS,
        *[o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()],
    ]
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'apps'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'apps.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'IMDb.urls'
AUTH_USER_MODEL = 'apps.User'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.context_processors.site_cfg',
            ],
        },
    },
]

WSGI_APPLICATION = 'IMDb.wsgi.application'


# Database (lokalda SQLite, prod da DATABASE_URL env orqali)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_database_url = os.getenv('DATABASE_URL')
if _database_url and _database_url.startswith('postgres'):
    from urllib.parse import urlparse
    parsed = urlparse(_database_url)
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed.path.lstrip('/'),
        'USER': parsed.username,
        'PASSWORD': parsed.password,
        'HOST': parsed.hostname,
        'PORT': parsed.port or '5432',
        'CONN_MAX_AGE': 60,
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
if DEBUG:
    # Dev da manifest ishlamaydi — to'g'ridan-to'g'ri fayl xizmat qiladi
    STORAGES['staticfiles']['BACKEND'] = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# MEDIA fayllarni obyekt saqlashga ko'chirish (Cloudflare R2 / AWS S3).
# R2 sozlash (bepul):
#   AWS_ACCESS_KEY_ID=r2 token id
#   AWS_SECRET_ACCESS_KEY=r2 token secret
#   AWS_S3_REGION_NAME=auto
#   AWS_S3_ENDPOINT_URL=https://<bucket_id>.r2.cloudflarestorage.com
#   AWS_STORAGE_BUCKET_NAME=<bucket>
#   MEDIA_URL=https://pub-<id>.r2.dev/
# Yoki AWS S3: standart S3 uchun endpoint URL qo'ymasangiz AWS S3 ishlatiladi.
_AWS_ACTIVE = bool(
    os.getenv('AWS_ACCESS_KEY_ID')
    and os.getenv('AWS_S3_ENDPOINT_URL')
    and os.getenv('AWS_STORAGE_BUCKET_NAME')
)
if _AWS_ACTIVE:
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'bucket_name': os.getenv('AWS_STORAGE_BUCKET_NAME'),
            'endpoint_url': os.getenv('AWS_S3_ENDPOINT_URL'),
            'region_name': os.getenv('AWS_S3_REGION_NAME', 'auto'),
            'default_acl': 'public-read' if not env_bool('AWS_S3_PRIVATE', False) else None,
            'querystring_auth': env_bool('AWS_S3_PRIVATE', False),
            'signature_version': 's3v4',
        },
    }

MEDIA_URL = os.getenv('MEDIA_URL', 'media/')
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'

# Security
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', False)
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = bool(SECURE_HSTS_SECONDS)
SECURE_HSTS_PRELOAD = bool(SECURE_HSTS_SECONDS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Email (dev da parol tiklash xatolari konsolga chiqadi)
EMAIL_BACKEND = os.getenv(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('DJANGO_EMAIL_USE_TLS', True)
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'CINEMA <noreply@cinema.local>')

# Telegram (film videolarini import qilish uchun)
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')

# Cache: REDIS_URL ko'rsatilsa Redis (locmem emas), aks holda xotirada.
# Redis bo'lsa rate-limit hisoblagichlari server qayta ishga tushganda ham saqlanadi.
_REDIS_URL = os.getenv('REDIS_URL', '').strip()
if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'cinema-cache',
        }
    }
if not DEBUG and not _REDIS_URL:
    # LocMemCache gunicorn worker'lar orasida bo'linmaydi — rate-limit ishlamay qoladi.
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('REDIS_URL prod da ko\'rsatilishi shart (cache va rate-limit uchun)')

# Google Analytics / Tag Manager (GA4: G-XXXXXXXXXX)
GOOGLE_TAG_ID = os.getenv('GOOGLE_TAG_ID', '')

# Logging: konsol (dev) + aylanuvchi fayl (prod, kutilmagan xatolar uchun)
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)
_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'app.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': _LOG_LEVEL,
    },
    'loggers': {
        'PIL': {
            'handlers': [],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Sentry (xatolarni kuzatish) — SENTRY_DSN bilan yoqiladi
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
        integrations=[DjangoIntegration()],
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


UNFOLD = {
    "SITE_TITLE": 'CINEMA Admin',
    "SITE_HEADER": 'CINEMA Admin',
    "SITE_URL": '/',
    "SITE_SYMBOL": 'movie',
    "DASHBOARD_CALLBACK": 'apps.utils.dashboard_callback',
    "LOGIN": {
        "image": None,
        "title": 'CINEMA',
        "subtitle": 'Kinoning boshqaruv markazi',
    },
    "SHOW_HISTORY": True,
    "SHOW_VIEWS_ON_SITE": True,
    "SHOW_UNFOLD_LOGIN": True,
    "COLORS": {
        "primary": {
            "50": "250 245 240",
            "100": "244 233 219",
            "200": "232 210 181",
            "300": "220 187 143",
            "400": "210 166 110",
            "500": "197 148 80",
            "600": "175 122 58",
            "700": "146 98 48",
            "800": "120 81 43",
            "900": "91 62 38",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": 'Kino',
                "separator": True,
                "items": [
                    {
                        "title": 'Filmlar',
                        "icon": 'movie',
                        "link": '/admin/apps/movie/',
                    },
                    {
                        "title": 'Janrlar',
                        "icon": 'category',
                        "link": '/admin/apps/genre/',
                    },
                    {
                        "title": 'Aktyorlar va jamoa',
                        "icon": 'group',
                        "link": '/admin/apps/person/',
                    },
                ],
            },
            {
                "title": 'Foydalanuvchilar',
                "separator": True,
                "items": [
                    {
                        "title": 'Foydalanuvchilar',
                        "icon": 'person',
                        "link": '/admin/apps/user/',
                    },
                    {
                        "title": 'Saqlangan ro\'yxatlar',
                        "icon": 'bookmark',
                        "link": '/admin/apps/watchlistitem/',
                    },
                    {
                        "title": 'Guruhlar',
                        "icon": 'group',
                        "link": '/admin/auth/group/',
                    },
                ],
            },
        ],
    },
    "STYLES": [
        'admin/css/unfold_extra.css',
    ],
}
