# Generated by Django 5.2.16 on 2026-08-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_legacy_ratings(apps, schema_editor):
    Movie = apps.get_model('apps', 'Movie')
    Movie.objects.update(rating=None, rating_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_movie_options_movie_genres_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Baholar soni (avtomatik)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Foydalanuvchilar bahosining o'rtachasi (avtomatik)", max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='apps.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.RunPython(clear_legacy_ratings),
    ]
