# Generated by Django 5.2.16 on 2026-08-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_movie_rating_count_alter_movie_rating_movierating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed havolasi (https://www.youtube.com/embed/...)', max_length=500, null=True),
        ),
    ]
