# Generated by Django 5.2.16 on 2026-08-06 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_movie_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Qisqa biografiya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': "Aktyor / jamoa a'zosi",
                'verbose_name_plural': 'Aktyorlar va jamoa',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='box_office',
            field=models.PositiveBigIntegerField(blank=True, help_text="Kassa yig'imi (USD)", null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.PositiveBigIntegerField(blank=True, help_text='Byudjet (USD)', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='certificate',
            field=models.CharField(blank=True, choices=[('all', 'Barcha yosh'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], help_text='Yosh cheklovi (16+, 18+ ...)', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, help_text='Mamlakat (masalan: AQSh)', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, help_text='Asosiy til (masalan: Inglizcha)', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.CharField(blank=True, help_text='Kino studiyasi', max_length=200),
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Fikr-mulohazangiz', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apps.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('movie', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Aktyor'), ('director', 'Rejissyor'), ('writer', 'Ssenariy muallifi'), ('producer', 'Produser'), ('composer', 'Kompozitor')], default='actor', max_length=20)),
                ('character_name', models.CharField(blank=True, help_text="Aktyor o'ynagan qahramon nomi (faqat aktyorlar uchun)", max_length=255)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='apps.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='apps.person')),
            ],
            options={
                'ordering': ['role', 'person__full_name'],
                'unique_together': {('movie', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='apps.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
