# Generated by Django 5.2.16 on 2026-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_person_movie_box_office_movie_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text="YouTube havolasi yoki to'g'ridan-to'g'ri video URL (mp4, Telegram fayl havolasi)", max_length=500, null=True),
        ),
    ]
