# Generated by Django 5.2.16 on 2026-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, help_text='Asl nomi (masalan: Крёстный отец) — qidiruv uchun', max_length=255, null=True),
        ),
    ]
