# Generated by Django 5.2.16 on 2026-08-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_movie_original_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Sitemap lastmod uchun (avtomatik)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text="YouTube treyler havolasi (sayt IMDb kabi katalog; faqat treyler ko'rsatiladi. Masalan: https://youtu.be/... yoki to'g'ridan-to'g'ri mp4)", max_length=500, null=True),
        ),
    ]
