# Generated by Django 5.2.16 on 2026-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_movie_updated_at_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, help_text="Keng formatli banner (16:9, tavsiya 1600x900) — bosh sahifa slayderi uchun; bo'sh qolsa poster ishlatiladi", null=True, upload_to='banners/'),
        ),
    ]
