# Generated by Django 5.2.16 on 2026-08-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_movie_banner_moviedailyviews_watchedmovie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedmovie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='watchedmovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchedmovie',
            name='user',
        ),
        migrations.DeleteModel(
            name='MovieDailyViews',
        ),
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
