# Generated by Django 5.2.16 on 2026-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_watchedmovie_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text="YouTube treyler havolasi (faqat treyler ko'rsatiladi). Masalan: https://youtu.be/... yoki to'g'ridan-to'g'ri mp4", max_length=500, null=True),
        ),
    ]
