# Generated by Django 5.2.16 on 2026-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_movie_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': [models.OrderBy(models.F('rating'), descending=True, nulls_last=True), models.OrderBy(models.F('views_count'), descending=True)]},
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Sitemap lastmod uchun (avtomatik)'),
        ),
    ]
