# Generated by Django 5.2.16 on 2026-08-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_movie_options_person_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search_text',
            field=models.TextField(blank=True, default='', help_text='Qidiruv uchun normalizatsiyalangan matn (avtomatik)'),
        ),
    ]
