# Generated by Django 5.2.16 on 2026-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_backfill_search_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='search_text',
            field=models.TextField(blank=True, db_index=True, default='', help_text='Qidiruv uchun normalizatsiyalangan matn (avtomatik)'),
        ),
    ]
